// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fthfohyzqqzoflskdgir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0aGZvaHl6cXF6b2Zsc2tkZ2lyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNzAzODgsImV4cCI6MjA2MDc0NjM4OH0.umdEMebFr4rpQtPI4O5ruG_rvSfQPJZ8M6RhlZ6zLho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);